<MainContent>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.3
        Rectangle:
            pos: self.pos
            size: self.size
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        Image:
            size_hint: 0.8, 0.8
            id: video_feed
            allow_stretch: True
            keep_ratio: True
            size: self.texture_size if self.texture else (0, 0)
